# Generated by Django 6.0 on 2025-12-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('issue_type', models.CharField(choices=[('General', 'General Query'), ('Order', 'Order Related'), ('Payment', 'Payment Issue'), ('Return', 'Return / Refund'), ('Technical', 'Technical Problem')], max_length=50)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
