# Generated by Django 6.0 on 2025-12-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
