# Generated by Django 6.0 on 2026-01-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_paymentproof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentproof',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='email',
            field=models.EmailField(default='noemail@rcshop.co.in', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
