# Generated by Django 6.0 on 2026-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_customer_order_is_paid_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='temp_order_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
